### ISSUE TITLE
URL Issue

### ISSUE THREAD

**Issue by frazras** [fiatjaf/lnurlpos-app#1]
I doubt this is an issue with the app, maybe just how I am configuring it.
Below are the screenshots when using the Wallet of Satoshi

![Screenshot 2021-12-15 at 8 39 23 AM](https://user-images.githubusercontent.com/177070/146188281-b1e931ed-f3a5-4197-b1e6-c3e8e18b95bf.png)
![IMG_0967](https://user-images.githubusercontent.com/177070/146188374-2d89628d-d08d-41c1-840b-b16fa01ccec3.PNG)
![IMG_0966](https://user-images.githubusercontent.com/177070/146188382-cb047088-57d8-4799-9f8e-e335ff65e4a3.PNG)

**Comment by frazras** [comment]
This is the message from Phoenix wallet
![IMG_BF16736D88B1-1](https://user-images.githubusercontent.com/177070/146189153-dd717909-d46d-45f6-b8ae-2920ef1555e0.jpeg)

**Comment by fiatjaf** [comment]
It is working!

The error was due to a malformed callback URL derived from a broken setting on infinity.lnbits.com, fixed now.

**Comment by frazras** [comment]
Awesome!
Works for me as well.
I'll work on setting up a distribution channel for the iOS app on Firebase next.

**Comment by frazras** [comment]
Just a side note, we need to open a UX issue for copying the settings from LNBits. It would be nice to generate that QR code in LN Bits with all the details bundeled
